# productservice/src/main/resources/application.properties
server.port=8080
spring.application.name=productservice
spring.profiles.active=dev

# Swagger values - unique per service
swagger.title=Product Service API
swagger.description=API documentation for Product Service
swagger.group=product-service
swagger.base-package=com.einfochips
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.mvc.pathmatch.use-suffix-pattern=false
# Show both services in one UI
springdoc.swagger-ui.urls[0].name=product-service
springdoc.swagger-ui.urls[0].url=/v3/api-docs/product-service
springdoc.swagger-ui.urls[1].name=user-service
springdoc.swagger-ui.urls[1].url=http://localhost:8081/v3/api-docs/user-service
# Database
spring.datasource.url=jdbc:mysql://localhost:3306/einfochips1
spring.datasource.username=root
spring.datasource.password=Kinu@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
