# ===============================
# Basic App Config
# ===============================
server.port=8080
spring.application.name=productservice
spring.main.web-application-type=servlet


# ===============================
# Database
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/einfochips1
spring.datasource.username=root
spring.datasource.password=Kinu@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true




# ===============================
# CORS
# ===============================
app.cors.allowed-origins=http://localhost:8080,http://localhost:8081


springdoc.swagger-ui.enabled=true

# Swagger grouping
swagger.group=product-service
swagger.base-package=com.einfochips.productservice.controllers
swagger.title=Product Service API
swagger.description=Product APIs

# Aggregator
springdoc.swagger-ui.urls[0].name=Product Service
springdoc.swagger-ui.urls[0].url=http://localhost:8080/v3/api-docs

springdoc.swagger-ui.urls[1].name=User Service
springdoc.swagger-ui.urls[1].url=http://localhost:8081/v3/api-docs