# Database
spring.datasource.url=jdbc:mysql://localhost:3306/einfochips
spring.datasource.username=root
spring.datasource.password=Kinu@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.mvc.pathmatch.use-suffix-pattern=false

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# userservice/src/main/resources/application.properties
# userservice/src/main/resources/application.properties
server.port=8081
spring.application.name=userservice
spring.profiles.active=dev

# Swagger values - unique per service
swagger.title=User Service API
swagger.description=API documentation for User Service
swagger.group=user-service
swagger.base-package=com.einfochips
app.default.password=Temp@12345ssssss
# JWT
jwt.secret=dGhpcysaXMtbXktc2VjcmV0LWtleS10aGF0LWlzLTI1Ni1iaXQtbG9uZw==
jwt.expiration=86400000

# Logging
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.userservice=DEBUG

# Uncomment below to log to file
# logging.file.name=logs/app.log
# logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n